// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAngAWUZhyBeI4bQ8HL7sfv0nYRN6T_EK4',
    appId: '1:441726084130:web:352db37689e9cd2ef0567b',
    messagingSenderId: '441726084130',
    projectId: 'weights-19184',
    authDomain: 'weights-19184.firebaseapp.com',
    storageBucket: 'weights-19184.appspot.com',
    measurementId: 'G-PJM2JRBW1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw0qWzU1WPfIzq8942Gl_0DD24pKFax4I',
    appId: '1:441726084130:android:6a2ca11ec20c83c1f0567b',
    messagingSenderId: '441726084130',
    projectId: 'weights-19184',
    storageBucket: 'weights-19184.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6LQp2IPzopwvukE4sIR8-QV_M7fYI3qk',
    appId: '1:441726084130:ios:358ec5fef8ac011cf0567b',
    messagingSenderId: '441726084130',
    projectId: 'weights-19184',
    storageBucket: 'weights-19184.appspot.com',
    iosBundleId: 'com.example.weightsKeeping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6LQp2IPzopwvukE4sIR8-QV_M7fYI3qk',
    appId: '1:441726084130:ios:358ec5fef8ac011cf0567b',
    messagingSenderId: '441726084130',
    projectId: 'weights-19184',
    storageBucket: 'weights-19184.appspot.com',
    iosBundleId: 'com.example.weightsKeeping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAngAWUZhyBeI4bQ8HL7sfv0nYRN6T_EK4',
    appId: '1:441726084130:web:cc686c1479617faef0567b',
    messagingSenderId: '441726084130',
    projectId: 'weights-19184',
    authDomain: 'weights-19184.firebaseapp.com',
    storageBucket: 'weights-19184.appspot.com',
    measurementId: 'G-NE222FKYGP',
  );

}